Repository openvm-org/openvm, pull requests merged in 2025-01, with the labels that each got.

#1150 chore: leaf aggregation tuning
  benchmarks/README.md
  benchmarks/src/bin/ecrecover.rs
  benchmarks/src/utils.rs
  crates/circuits/sha256-air/src/trace.rs
  crates/sdk/src/keygen/mod.rs
  crates/sdk/src/prover/agg.rs
  crates/sdk/src/prover/root.rs
  crates/sdk/src/prover/vm/local.rs
  docs/crates/metrics.md
Labels: run-benchmark

#1152 perf(recursion): remove extraneous functions from `TwoAdicPcs` verify
  .github/workflows/benchmarks.yml
  extensions/native/circuit/examples/fibonacci.rs
  extensions/native/recursion/src/fri/mod.rs
  extensions/native/recursion/src/fri/two_adic_pcs.rs
Labels: run-benchmark, run-benchmark-e2e

#1164 chore(prof): uniformize halo2 metrics and add aggregate summary
  .github/workflows/benchmarks.yml
  ci/scripts/bench.py
  ci/scripts/metric_unify/aggregation.json
  ci/scripts/metric_unify/example_metrics.json
  crates/prof/data/metrics.example.json
  crates/prof/data/metrics.prev.example.json
  crates/prof/src/aggregate.rs
  crates/prof/src/summary.rs
  crates/sdk/src/prover/agg.rs
  crates/sdk/src/prover/halo2.rs
  crates/vm/src/metrics/mod.rs
  docs/crates/metrics.md
  extensions/native/recursion/src/halo2/mod.rs
  extensions/native/recursion/src/halo2/wrapper.rs
Labels: run-benchmark, run-benchmark-e2e

#1169 perf: lock-free cycle count increment
  benchmarks/benches/regex_execute.rs
  benchmarks/examples/regex_execute.rs
  crates/vm/src/metrics/mod.rs
Labels: run-benchmark

#1187 feat: quotient polynomial evaluation from serialized constraints
  Cargo.lock
  Cargo.toml
  benchmarks/src/bin/verify_fibair.rs
  crates/vm/src/arch/integration_api.rs
Labels: run-benchmark

#1194 perf: Move range checks to trace gen
  extensions/native/circuit/src/castf/core.rs
  extensions/rv32im/circuit/src/adapters/hintstore.rs
  extensions/rv32im/circuit/src/adapters/loadstore.rs
  extensions/rv32im/circuit/src/jalr/core.rs
  extensions/rv32im/circuit/src/shift/core.rs
Labels: run-benchmark-e2e

#1176 feat: add iterator-based for loops
  .github/workflows/build.yml
  Cargo.lock
  extensions/native/compiler/derive/src/lib.rs
  extensions/native/compiler/src/asm/compiler.rs
  extensions/native/compiler/src/ir/builder.rs
  extensions/native/compiler/src/ir/collections.rs
  extensions/native/compiler/src/ir/instructions.rs
  extensions/native/compiler/src/ir/poseidon.rs
  extensions/native/compiler/src/ir/utils.rs
  extensions/native/compiler/tests/for_loops.rs
  extensions/native/recursion/Cargo.toml
  extensions/native/recursion/src/challenger/duplex.rs
  extensions/native/recursion/src/fri/mod.rs
  extensions/native/recursion/src/fri/two_adic_pcs.rs
  extensions/native/recursion/src/hints.rs
  extensions/native/recursion/src/stark/mod.rs
Labels: run-benchmark, run-benchmark-e2e

#1138 feat: vectorize native load store
  crates/vm/tests/integration_test.rs
  docs/specs/ISA.md
  docs/specs/RISCV.md
  extensions/native/circuit/src/adapters/loadstore_native_adapter.rs
  extensions/native/circuit/src/extension.rs
  extensions/native/circuit/src/loadstore/core.rs
  extensions/native/circuit/src/loadstore/tests.rs
  extensions/native/compiler/src/asm/compiler.rs
  extensions/native/compiler/src/asm/instruction.rs
  extensions/native/compiler/src/conversion/mod.rs
  extensions/native/compiler/src/lib.rs
Labels: run-benchmark, run-benchmark-e2e

#1231 chore: cleanup num2bits
  extensions/native/compiler/src/asm/compiler.rs
  extensions/native/compiler/src/ir/bits.rs
  extensions/native/compiler/src/ir/instructions.rs
  extensions/native/compiler/tests/hint.rs
  extensions/native/recursion/src/halo2/tests/mod.rs
Labels: run-benchmark, run-benchmark-e2e

#1175 use mul add in babybear felt ops
  benchmarks/Cargo.toml
  extensions/native/compiler/src/constraints/halo2/baby_bear.rs
  extensions/native/recursion/src/fri/two_adic_pcs.rs
Labels: run-benchmark-e2e

#1219 Feat: Native Poseidon2 chip
  Cargo.lock
  Cargo.toml
  crates/toolchain/instructions/src/lib.rs
  crates/vm/src/arch/testing/mod.rs
  crates/vm/tests/integration_test.rs
  docs/specs/ISA.md
  extensions/native/circuit/Cargo.toml
  extensions/native/circuit/src/extension.rs
  extensions/native/circuit/src/poseidon2/air.rs
  extensions/native/circuit/src/poseidon2/chip.rs
  extensions/native/circuit/src/poseidon2/columns.rs
  extensions/native/circuit/src/poseidon2/mod.rs
  extensions/native/circuit/src/poseidon2/tests.rs
  extensions/native/circuit/src/poseidon2/trace.rs
  extensions/native/compiler/src/asm/compiler.rs
  extensions/native/compiler/src/asm/instruction.rs
  extensions/native/compiler/src/conversion/mod.rs
  extensions/native/compiler/src/ir/instructions.rs
  extensions/native/compiler/src/ir/mod.rs
  extensions/native/compiler/src/ir/verify_batch.rs
  extensions/native/compiler/src/lib.rs
  extensions/native/recursion/src/fri/mod.rs
  extensions/native/recursion/src/fri/two_adic_pcs.rs
Labels: run-benchmark, run-benchmark-e2e

#1236 feat: optimize computation of generator exponents
  extensions/native/compiler/src/constraints/halo2/compiler.rs
  extensions/native/recursion/src/fri/two_adic_pcs.rs
Labels: run-benchmark, run-benchmark-e2e

#1244 [chore] Optimize `alpha_pow` computation
  extensions/native/compiler/src/ir/builder.rs
  extensions/native/compiler/src/ir/symbolic.rs
  extensions/native/recursion/src/fri/two_adic_pcs.rs
Labels: run-benchmark

#1250 [chore] Optimize Static Verifier alpha pow computation
  extensions/native/compiler/src/constraints/halo2/baby_bear.rs
  extensions/native/compiler/src/constraints/halo2/compiler.rs
  extensions/native/compiler/src/ir/instructions.rs
  extensions/native/compiler/src/ir/utils.rs
  extensions/native/recursion/src/fri/two_adic_pcs.rs
Labels: run-benchmark, run-benchmark-e2e

#1261 [perf] Optimize alpha_pow for Static Verifier
  benchmarks/src/utils.rs
  extensions/native/recursion/src/fri/two_adic_pcs.rs
Labels: run-benchmark-e2e

#1284 perf: update `stark-backend` to v0.3.0
  Cargo.lock
  Cargo.toml
  crates/prof/src/aggregate.rs
Labels: run-benchmark

#1280 change to inner product
  extensions/native/compiler/src/constraints/halo2/baby_bear.rs
Labels: run-benchmark-e2e

#1287 perf: `stark-backend` v0.4 with better interaction chunking
  .github/workflows/benchmarks.yml
  Cargo.lock
  Cargo.toml
  benchmarks/src/utils.rs
  crates/sdk/src/config/mod.rs
  crates/sdk/src/keygen/mod.rs
  crates/sdk/tests/integration_test.rs
Labels: run-benchmark, run-benchmark-e2e

#1293 chore: `stark-backend` v0.4.1
  .github/workflows/benchmarks.yml
  Cargo.lock
  Cargo.toml
Labels: run-benchmark, run-benchmark-e2e

#1306 fix: remove incorrect nop transpilation for intrinsics
  crates/toolchain/transpiler/src/util.rs
  docs/specs/RISCV.md
  extensions/algebra/transpiler/src/lib.rs
  extensions/bigint/transpiler/src/lib.rs
  extensions/ecc/transpiler/src/lib.rs
  extensions/keccak256/transpiler/src/lib.rs
  extensions/pairing/transpiler/src/lib.rs
  extensions/rv32im/transpiler/src/rrs.rs
  extensions/sha256/transpiler/src/lib.rs
Labels: run-benchmark-e2e

#1323 perf: Remove touch address for VolatileMemory
  crates/vm/src/system/memory/controller/interface.rs
  crates/vm/src/system/memory/volatile/mod.rs
Labels: run-benchmark, run-benchmark-e2e

#1325 [chore] Add more cycle tracker for hint
  extensions/native/recursion/src/fri/hints.rs
  extensions/native/recursion/src/fri/types.rs
  extensions/native/recursion/src/hints.rs
Labels: run-benchmark
