Repository openvm-org/openvm, pull requests merged in 2025-03, with the labels that each got.

#1413 feat: thinner pairing circuit
  .github/workflows/benchmark-call.yml
  Cargo.lock
  benchmarks/Cargo.toml
  benchmarks/programs/pairing/Cargo.toml
  benchmarks/programs/pairing/src/main.rs
  benchmarks/src/bin/pairing.rs
  ci/benchmark-config.json
  crates/circuits/mod-builder/src/core_chip.rs
  crates/cli/src/default.rs
  crates/sdk/src/config/mod.rs
  docs/specs/ISA.md
  docs/specs/RISCV.md
  docs/specs/isa-table.md
  docs/specs/transpiler.md
  extensions/pairing/circuit/src/pairing_extension.rs
  extensions/pairing/guest/src/bls12_381/fp12.rs
  extensions/pairing/guest/src/bls12_381/mod.rs
  extensions/pairing/guest/src/bls12_381/pairing.rs
  extensions/pairing/guest/src/bn254/fp12.rs
  extensions/pairing/guest/src/bn254/mod.rs
  extensions/pairing/guest/src/bn254/pairing.rs
  extensions/pairing/guest/src/halo2curves_shims/bn254/mod.rs
  extensions/pairing/guest/src/lib.rs
  extensions/pairing/guest/src/pairing/miller_step.rs
  extensions/pairing/guest/src/pairing/mod.rs
  extensions/pairing/guest/src/pairing/sextic_ext_field.rs
  extensions/pairing/tests/programs/examples/fp12_mul.rs
  extensions/pairing/tests/programs/examples/pairing_line.rs
  extensions/pairing/transpiler/src/lib.rs
Labels: run-benchmark

#1445 fix: Don't segment if continuation is disabled
  crates/vm/src/arch/segment.rs
Labels: run-benchmark-e2e

#1449 fix: update stark-backend to protect against weak Fiat-Shamir
  Cargo.lock
  Cargo.toml
  crates/vm/src/arch/vm.rs
  extensions/native/recursion/src/config/outer.rs
  extensions/native/recursion/src/stark/mod.rs
  extensions/native/recursion/src/types.rs
Labels: run-benchmark, run-benchmark-e2e

#1441 tests: add kitchen-sink e2e benchmark
  benchmarks/programs/kitchen-sink/Cargo.toml
  benchmarks/programs/kitchen-sink/src/main.rs
  benchmarks/src/bin/kitchen_sink.rs
  ci/benchmark-config.json
Labels: run-benchmark-e2e

#1479 refactor: Add type `EvmProof` into openvm-sdk
  Cargo.lock
  crates/sdk/Cargo.toml
  crates/sdk/src/fs.rs
  crates/sdk/src/lib.rs
  crates/sdk/src/prover/halo2.rs
  crates/sdk/src/prover/mod.rs
  crates/sdk/src/types.rs
  extensions/native/recursion/src/halo2/mod.rs
  extensions/native/recursion/src/halo2/wrapper.rs
Labels: run-benchmark-e2e, run-cli-e2e

#1491 docs: rust `std` vs `no-std`
  .github/workflows/lints.yml
  Cargo.lock
  benchmarks/programs/base64_json/Cargo.toml
  benchmarks/programs/base64_json/src/lib.rs
  benchmarks/programs/base64_json/src/main.rs
  benchmarks/programs/bincode/Cargo.toml
  benchmarks/programs/bincode/src/main.rs
  benchmarks/programs/ecrecover/Cargo.toml
  benchmarks/programs/ecrecover/src/main.rs
  benchmarks/programs/fibonacci/Cargo.toml
  benchmarks/programs/fibonacci/src/main.rs
  benchmarks/programs/pairing/Cargo.toml
  benchmarks/programs/pairing/src/main.rs
  benchmarks/programs/regex/Cargo.toml
  benchmarks/programs/regex/src/main.rs
  benchmarks/programs/revm_transfer/Cargo.toml
  benchmarks/programs/revm_transfer/src/main.rs
  benchmarks/programs/rkyv/Cargo.toml
  benchmarks/programs/rkyv/src/main.rs
  benchmarks/src/bin/revm_transfer.rs
  book/src/getting-started/quickstart.md
  book/src/writing-apps/write-program.md
  crates/toolchain/openvm/Cargo.toml
  crates/toolchain/platform/src/getrandom.rs
  examples/algebra/Cargo.toml
  examples/algebra/src/main.rs
  examples/ecc/Cargo.toml
  examples/ecc/src/main.rs
  examples/i256/Cargo.toml
  examples/i256/src/main.rs
  examples/keccak/Cargo.toml
  examples/keccak/src/main.rs
  examples/pairing/Cargo.toml
  examples/pairing/src/main.rs
  examples/sha256/Cargo.toml
  examples/sha256/src/main.rs
  examples/u256/Cargo.toml
  examples/u256/src/main.rs
  extensions/algebra/guest/Cargo.toml
  extensions/algebra/tests/programs/Cargo.toml
  extensions/bigint/guest/Cargo.toml
  extensions/bigint/guest/src/i256.rs
  extensions/bigint/guest/src/lib.rs
  extensions/bigint/guest/src/u256.rs
  extensions/bigint/tests/programs/Cargo.toml
  extensions/ecc/guest/Cargo.toml
  extensions/ecc/tests/programs/Cargo.toml
  extensions/keccak256/guest/Cargo.toml
  extensions/keccak256/guest/src/lib.rs
  extensions/keccak256/tests/programs/Cargo.toml
  extensions/pairing/guest/Cargo.toml
  extensions/pairing/guest/src/tests/ec_msm.rs
  extensions/pairing/guest/src/tests/mod.rs
  extensions/pairing/tests/programs/Cargo.toml
  extensions/rv32im/tests/programs/Cargo.toml
  extensions/sha256/guest/Cargo.toml
  extensions/sha256/guest/src/lib.rs
  extensions/sha256/tests/programs/Cargo.toml
Labels: run-benchmark, run-benchmark-e2e, run-cli-e2e

#1502 feat(recursion): observe AIR IDs in verifier
  Cargo.lock
  Cargo.toml
  extensions/native/recursion/src/stark/mod.rs
Labels: run-benchmark

#1503 feat(recursion): add clarifying OOB check
  Cargo.lock
  Cargo.toml
  extensions/native/recursion/src/stark/mod.rs
Labels: run-benchmark, run-benchmark-e2e

#1537 fix: plonky3 FRI verifier
  Cargo.lock
  Cargo.toml
  audits/v1-internal/stark-backend.md
Labels: run-benchmark, run-benchmark-e2e, run-cli-e2e

#1540 release: v1.0.0
  Cargo.lock
  Cargo.toml
Labels: run-benchmark, run-benchmark-e2e, run-cli-e2e
