Repository openvm-org/openvm, pull requests merged in 2025-02, with the labels that each got.

#1328 [perf] VerifyBatch direct hint
  docs/specs/ISA.md
  extensions/native/circuit/src/extension.rs
  extensions/native/circuit/src/poseidon2/README.md
  extensions/native/circuit/src/poseidon2/air.rs
  extensions/native/circuit/src/poseidon2/chip.rs
  extensions/native/circuit/src/poseidon2/columns.rs
  extensions/native/circuit/src/poseidon2/tests.rs
  extensions/native/circuit/src/poseidon2/trace.rs
  extensions/native/compiler/src/asm/compiler.rs
  extensions/native/compiler/src/asm/instruction.rs
  extensions/native/compiler/src/conversion/mod.rs
  extensions/native/compiler/src/ir/builder.rs
  extensions/native/compiler/src/ir/instructions.rs
  extensions/native/compiler/src/ir/types.rs
  extensions/native/compiler/src/ir/verify_batch.rs
  extensions/native/recursion/src/fri/hints.rs
  extensions/native/recursion/src/fri/mod.rs
  extensions/native/recursion/src/fri/types.rs
  extensions/native/recursion/src/fri/witness.rs
  extensions/native/recursion/src/vars.rs
Labels: run-benchmark, run-benchmark-e2e

#1344 perf: optimize poseidon
  extensions/native/compiler/src/constraints/halo2/poseidon2_perm.rs
Labels: run-benchmark-e2e

#1347 [perf] `opened_values` direct hint
  crates/vm/src/system/memory/offline_checker/columns.rs
  docs/specs/ISA.md
  extensions/native/circuit/src/extension.rs
  extensions/native/circuit/src/fri/mod.rs
  extensions/native/circuit/src/fri/tests.rs
  extensions/native/compiler/derive/src/lib.rs
  extensions/native/compiler/src/asm/compiler.rs
  extensions/native/compiler/src/asm/instruction.rs
  extensions/native/compiler/src/conversion/mod.rs
  extensions/native/compiler/src/ir/collections.rs
  extensions/native/compiler/src/ir/fri.rs
  extensions/native/compiler/src/ir/instructions.rs
  extensions/native/compiler/src/ir/types.rs
  extensions/native/compiler/tests/fri_ro_eval.rs
  extensions/native/recursion/src/fri/hints.rs
  extensions/native/recursion/src/fri/mod.rs
  extensions/native/recursion/src/fri/two_adic_pcs.rs
  extensions/native/recursion/src/fri/types.rs
  extensions/native/recursion/src/fri/witness.rs
Labels: run-benchmark, run-benchmark-e2e

#1351 chore: Prefer log_height to height
  extensions/native/circuit/src/poseidon2/air.rs
  extensions/native/circuit/src/poseidon2/chip.rs
  extensions/native/circuit/src/poseidon2/columns.rs
  extensions/native/circuit/src/poseidon2/tests.rs
  extensions/native/circuit/src/poseidon2/trace.rs
  extensions/native/recursion/src/fri/domain.rs
  extensions/native/recursion/src/fri/mod.rs
  extensions/native/recursion/src/fri/two_adic_pcs.rs
  extensions/native/recursion/src/fri/types.rs
Labels: run-benchmark

#1352 perf: trivial opt to reduce alloc in recursion
  extensions/native/recursion/src/fri/two_adic_pcs.rs
Labels: run-benchmark
